stages:
  - build
  - deploy

build_master:
  only:
    - master
  stage: build
  image: node:16
  before_script:
    - node -v
    - npm -v
  script:
    - yarn
    - yarn build
  cache:
    key: node_modules_mgm_poc
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

deploy_master:
  only:
    - master
  stage: deploy
  environment:
    name: master
    url: https://mgm-poc.web.app
  image: andreysenov/firebase-tools:9.13.1-node12
  script:
    - firebase deploy --token $FIREBASE_TOKEN
